# name: Generate Datas
# on:
#   schedule: # execute every 12 hours
#     - cron: "0 */12 * * *"
#   workflow_dispatch: # manual trigger

# jobs:
#   build:
#     name: Jobs to update data
#     runs-on: ubuntu-latest
#     steps:
#       # Snake Animation
#       - name: generate-snake-game-from-github-contribution-grid
#         uses: Platane/snk@v3.2.0
#         id: snake-gif
#         with:
#           github_user_name: TheVinaySagar
#           svg_out_path: dist/github-contribution-grid-snake.svg

#       - name: Deploy to GitHub Pages
#         uses: crazy-max/ghaction-github-pages@v2.1.3
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger
  
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3.2.0
        id: snake-gif
        with:
          github_user_name: TheVinaySagar  # Replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
